"""Added trend_enabled column to Exercise table

Revision ID: 21b1ffb38539
Revises: 39513d76e8b8
Create Date: 2015-10-14 20:46:48.941000

"""

# revision identifiers, used by Alembic.
revision = '21b1ffb38539'
down_revision = '39513d76e8b8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import Integer


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('trend_enabled', sa.Integer()))
    ### end Alembic commands ###

    exercise_table = table('exercise',
        sa.Column('trend_enabled', Integer())
    )

    op.execute(
        exercise_table.update().\
            values({'trend_enabled':op.inline_literal(1)})
            )


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise', 'trend_enabled')
    ### end Alembic commands ###
