"""add column Color to Exercise

Revision ID: 39513d76e8b8
Revises:
Create Date: 2015-09-19 10:42:47.327000

"""

# revision identifiers, used by Alembic.
revision = '39513d76e8b8'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer, Date


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('color', sa.String(length=20), nullable=True))
    ### end Alembic commands ###

    exercise_table = table('exercise',
        sa.Column('color', String(20))
    )

    op.execute(
        exercise_table.update().\
            values({'color':op.inline_literal('#777')})
            )


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("exercise") as batch_op:
    	batch_op.drop_column('color')
    ### end Alembic commands ###
